export const heroSkills = {
	"Warrior": "skill_warrior",
	"Assassin": "skill_assassin",
	"Paladin": "skill_paladin",
	"Wizard": "skill_wizard",
	"Necromancer": "skill_necromancer",
	"Shaman": "skill_shaman",
	"Ranger": "skill_ranger",
	"Druid": "skill_druid",
	"Engineer": "skill_engineer",
	"Diamond Shield": "skill_1",
	"Knowledge of Strength": "skill_2",
	"Knowledge of Resistance": "skill_3",
	"Luxury Gift": "skill_4",
	"Toxic Wall": "skill_5",
	"Burning Wall": "skill_6",
	"Frost Nova": "skill_7",
	"Chain Lightning": "skill_8",
	"Bones Armor": "skill_9",
	"Bounty Hunter": "skill_10",
	"Soul Drain": "skill_11",
	"Explosive Enemies": "skill_12",
	"Toxic Strike": "skill_13",
	"Burning Strike": "skill_14",
	"Shuriken Attack": "skill_15",
	"Kunai Attack": "skill_16",
	"Gold Ingot": "skill_17",
	"Treasure Map": "skill_18",
	"Anti-monster Mine": "skill_19",
	"Telescope": "skill_20",
	"Apple Pie": "skill_21",
	"Torch": "skill_22",
	"Growth Blessing": "skill_23",
	"Potion Maker": "skill_24",
	"Kraken Tentacle": "skill_25",
	"Meteor Storm": "skill_26",
	"Mana Battery": "skill_27",
	"Ice Block": "skill_28",
	"Flame Aura": "skill_29",
	"Life Sword": "skill_30",
	"Necklace of Life": "skill_31",
	"Stone Skin": "skill_32",
	"Devil's Deal": "skill_33",
	"Wand of Combat": "skill_34",
	"Wand of Magic": "skill_35",
	"Mana Sword": "skill_36",
	"Shield of Shadows": "skill_37",
	"Fire Punch": "skill_38",
	"Thunder Blast": "skill_39",
	"Dark Sigil": "skill_40",
	"Tower Shield": "skill_41",
	"Blessing of Sanctuary": "skill_42",
	"Phoenix Feather": "skill_43",
	"Shadow Wall": "skill_44",
	"Dark Matter": "skill_45",
	"Demon Eye": "skill_46",
	"Living Mana": "skill_47",
	"Book of Magic": "skill_48",
	"Toxic Explosion": "skill_49",
	"Burning Armor": "skill_50",
	"Master of Toxins": "skill_51",
	"Frog Leg": "skill_52",
	"Fox Tail": "skill_53",
	"Rabbit Paw": "skill_54",
	"Phantom Boots": "skill_55",
	"Pink Magic": "skill_56",
	"Shadow Cage": "skill_57",
	"Solid Shell": "skill_58",
	"Multishot": "skill_59",
	"Priest Staff": "skill_60",
	"Ice King Sword": "skill_61",
	"Earth Punch": "skill_62",
	"Dark Grasp": "skill_63",
	"Golden Potion": "skill_64",
	"Staff of Bones": "skill_65",
	"Amulet of Healing": "skill_66",
	"Circular Shield": "skill_67",
	"Key of the Portal": "skill_68",
	"Staff of Curses": "skill_69",
	"Tear of Goddess": "skill_70",
	"Opal Stone": "skill_71",
	"Pickpocket": "skill_72",
	"Purple Magic": "skill_73",
	"Crystal Sphere": "skill_74",
	"Barbarian": "skill_barbarian",
	"Pirate": "skill_pirate",
	"Runemaster": "skill_runemaster",
	"Invisibility Potion": "skill_75",
	"Snail Shell": "skill_76",
	"Acid Arrow": "skill_77",
	"Toxic Aura": "skill_78",
	"Perfect Crystal": "skill_79",
	"Necronomicon": "skill_80",
	"Weakening Aura": "skill_81",
	"Finisher": "skill_82",
	"Purple Potion": "skill_83",
	"Electrostatic Field": "skill_84",
	"Explosive Shot": "skill_85",
	"Freezing Shot": "skill_86",
	"Spear of Ghosts": "skill_87",
	"Weak Vortex": "skill_88",
	"Golden Shield": "skill_89",
	"Toxic Globe": "skill_90",
	"Piece of Coal": "skill_91",
	"Cursed Arrow": "skill_92",
	"Bat Wing": "skill_93",
	"Bird Beak": "skill_94",
	"Weak Dagger": "skill_95",
	"Burn Dagger": "skill_96",
	"Thunder Dagger": "skill_97",
	"Rock Dagger": "skill_98",
	"Mana Dagger": "skill_99",
	"Sapphire Medallion": "skill_100",
	"Scorpion Claw": "skill_101",
	"Roc's Feather": "skill_102",
	"Forest Sigil": "skill_forest",
	"Swamp Sigil": "skill_swamp",
	"Desert Sigil": "skill_desert",
	"Deep Water Sigil": "skill_water",
	"Volcano Sigil": "skill_volcano",
	"Lost World Sigil": "skill_lostworld",
	"Land of Dragons Sigil": "skill_dragon",
	"Reign of the Dead Sigil": "skill_undead",
	"The Void Sigil": "skill_void",
	"Warden": "skill_warden",
	"Cultist": "skill_cultist",
	"Gladiator": "skill_gladiator",
	"Vial of Life": "skill_103",
	"Lure": "skill_104",
	"Destroyed Shield": "skill_105",
	"Services Voucher": "skill_106",
	"Power Battery": "skill_107",
	"Magician Hat": "skill_108",
	"War Hatchet": "skill_109",
	"Strange Potion": "skill_110",
	"Block of Gems": "skill_111",
	"Fully Charged": "skill_112",
	"Earth Trap": "skill_113",
	"Wild Strawberries": "skill_114",
	"Demon Blood": "skill_115",
	"Sacred Tunic": "skill_116",
	"Double Edged Blade": "skill_117",
	"Cardpedia": "skill_118",
	"Spiked Armor": "skill_119",
	"Spiked Shield": "skill_120",
	"Spiked Gloves": "skill_121",
	"Weakening Strike": "skill_122",
	"Thunder Strike": "skill_123",
	"Electrified Arrow": "skill_124",
	"Circular Strike": "skill_125",
	"Acid Spear": "skill_126",
	"Death Diary": "skill_127",
	"Stone Block": "skill_128",
	"Sun Blessed Mace": "skill_129",
	"Sun Blessed Bow": "skill_130",
	"Brightest Star": "skill_131",
	"Piercing Flames": "skill_132",
	"Infernal Skull": "skill_133",
	"Leather Helmet": "skill_134",
	"Leather Boots": "skill_135",
	"Black Shield": "skill_136",
	"Heavy Helmet": "skill_137",
	"Heavy Armor": "skill_138",
	"Heavy Shield": "skill_139",
	"Wood Elves Boots": "skill_140",
	"Dark Elves Boots": "skill_141",
	"Toxic Leaf": "skill_142",
	"Antidote": "skill_143",
	"Magic Mirror": "skill_144",
	"Evoker Staff": "skill_145",
	"Twin-blade Sword": "skill_146",
	"Staff of Ghosts": "skill_147",
	"Shooting Target": "skill_148",
	"Electrostatic Aura": "skill_149",
	"Water Geyser": "skill_150",
};
