export const heroCards = {
	"Fighter": "a_0",
	"Guard": "a_1",
	"Mage": "m_0",
	"Lava Boulder": "a_107",
	"Demon Bride [DEMON]": "m_52",
	"Demon Pawn [DEMON]": "m_26",
	"Apprentice Guard": "a_2",
	"Apprentice Knight": "a_3",
	"Apprentice Witch": "m_1",
	"Crimson Guard": "a_51",
	"Elf Warrior [ELF] *": "a_4",
	"Elf Warrior [ELF] **": "a_5",
	"Elf Warrior [ELF] ***": "a_6",
	"High Witch *": "m_2",
	"High Witch **": "m_3",
	"Wizard *": "m_4",
	"Wizard **": "m_5",
	"Wizard ***": "m_6",
	"Sapphire Guard": "a_7",
	"Young Fighter": "a_8",
	"Desert Fighter": "a_9",
	"Wood Ranger": "a_10",
	"Young Witch": "m_7",
	"Fire Priestess": "m_8",
	"Desert Priestess": "m_9",
	"Black Knight": "a_12",
	"Knight of the Sigil": "a_14",
	"Lady of the Dark Souls": "a_17",
	"Guardian of the Sigil": "m_12",
	"Angel Archer [ANGEL]": "a_24",
	"Angel Priestess [ANGEL]": "m_23",
	"Nephil [ANGEL]": "m_53",
	"Succubus [DEMON] *": "m_27",
	"Succubus [DEMON] **": "m_28",
	"Demon Guard [DEMON]": "a_26",
	"Lion Fighter [BEASTMAN]": "a_31",
	"Lizard Fighter [BEASTMAN]": "a_32",
	"Lizard Guard [BEASTMAN]": "a_33",
	"Toxic Cat [BEASTMAN]": "a_34",
	"Fire Cat [BEASTMAN]": "a_35",
	"Heavenly Cat [BEASTMAN]": "a_89",
	"Thunder Cat [BEASTMAN]": "a_119",
	"Medusa *": "m_30",
	"Medusa **": "m_31",
	"Spider Queen [BEASTMAN] *": "m_32",
	"Spider Queen [BEASTMAN] **": "m_33",
	"Mermaid Queen *": "a_41",
	"Mermaid Queen **": "a_42",
	"King Neptune *": "a_43",
	"King Neptune **": "a_44",
	"Night Fairy [FAIRY]": "m_36",
	"Ivy Fairy [FAIRY]": "m_37",
	"Elder Fairy [FAIRY]": "m_38",
	"Volcanic Fairy [FAIRY]": "m_39",
	"Blue Bloom [FAIRY]": "m_43",
	"Blue Bug": "evoke_10",
	"BangBot [ROBOT]": "a_46",
	"Flamethrower [ROBOT]": "m_44",
	"GorillaTron [ROBOT]": "a_47",
	"Sword Master": "a_11",
	"Imperial Guard": "a_13",
	"Vigilant": "a_15",
	"Dark shielded Knight": "a_16",
	"Mage Thief": "m_10",
	"High Priest": "m_11",
	"Souls Guardian": "m_13",
	"Forgotten Priestess": "m_14",
	"Snow Queen": "m_15",
	"Lady of the Knight": "m_16",
	"Cthool Acolyte": "a_23",
	"Angel Fighter [ANGEL]": "a_25",
	"Guardian of Heavens [ANGEL]": "m_24",
	"Fallen Angel [ANGEL][DEMON]": "a_27",
	"Living Armor [DEMON]": "a_30",
	"Ant Soldier [BEASTMAN]": "a_37",
	"Ant Wizard [BEASTMAN]": "m_29",
	"Snake Emperor [BEASTMAN]": "a_39",
	"Fairy Queen [FAIRY] *": "m_34",
	"Fairy Queen [FAIRY] **": "m_35",
	"Moon Fairy [FAIRY]": "m_40",
	"Fairy Warrior [FAIRY]": "a_45",
	"Lady Bloom [FAIRY]": "m_41",
	"Fairy of Thorns [FAIRY]": "m_42",
	"P0-B1 [ROBOT]": "m_45",
	"B0-P1 [ROBOT]": "m_46",
	"Dark Lord": "a_18",
	"Vampire Lord": "a_19",
	"Sacred Knight": "a_20",
	"Shadow Assassin": "a_21",
	"The Hammer of Fate": "a_22",
	"Dark Wizard": "m_17",
	"Wizard of Poison": "m_18",
	"Dark Lotus Witch": "m_19",
	"Toxic Plant": "evoke_5",
	"Fire Plant": "evoke_6",
	"Thorn Plant": "evoke_7",
	"Fire Thorn Plant": "evoke_8",
	"Witch of Flame": "m_20",
	"Wizard of Nature": "m_21",
	"Druid of the High Elves": "m_22",
	"Dragoniax": "evoke_1",
	"Dragonius": "evoke_2",
	"Unicorn": "evoke_3",
	"Pegaso": "evoke_4",
	"The Timeshifter [ANGEL]": "m_25",
	"Commander Armstrong [DEMON]": "a_28",
	"Guardian of the Demons [DEMON]": "a_29",
	"General Wukong [BEASTMAN]": "a_40",
	"Hyper Samurai [ROBOT]": "a_48",
	"RoboWitch [ROBOT]": "m_47",
	"Sentinel [ROBOT]": "m_48",
	"Robo Hound [ROBOT]": "evoke_9",
	"Ultron [ROBOT]": "m_49",
	"Ultron Battery [ROBOT]": "evoke_11",
	"Artillery Unit [ROBOT]": "a_49",
	"Hyper Warrior [ROBOT]": "a_50",
	"Fairy Doll [FAIRY]": "evoke_21",
	"Penguin": "evoke_22",
	"Oracle Statue": "evoke_23",
	"Flame Imp [DEMON]": "a_52",
	"Son of the Forest": "druid_1",
	"Daughter of the Forest": "druid_2",
	"Spirit of the Forest": "druid_3",
	"Snail Companion": "ranger_snail",
	"Wolf Companion": "ranger_wolf",
	"Snake Companion": "ranger_snake",
	"Squirrel Companion": "ranger_squirrel",
	"Golem Warrior": "wiz_2",
	"Mud Golem": "wiz_3",
	"Energy Golem": "wiz_1",
	"Hitman": "assassin_1",
	"Black Widow": "assassin_2",
	"Assassin Master": "assassin_3",
	"Skeleton Fighter": "necro_1",
	"Banshee": "necro_3",
	"Mace Skeleton": "necro_2",
	"Undead Army Fighter": "necro_4",
	"Mechanic": "eng_1",
	"Scientist": "eng_2",
	"Activation Gear [ROBOT]": "eng_3",
	"Rifle Unit [ROBOT]": "eng_evoke_1",
	"Laser Unit [ROBOT]": "eng_evoke_2",
	"Cannon Unit [ROBOT]": "eng_evoke_3",
	"Armored Unit [ROBOT]": "eng_evoke_4",
	"Maid Unit [ROBOT]": "eng_evoke_0",
	"Time Machine [ROBOT]": "eng_evoke_5",
	"Souls Priestess": "m_50",
	"Spheres of Duplication [ROBOT]": "m_51",
	"Robo Wasp [ROBOT]": "a_53",
	"Iron Colossus [ROBOT]": "a_54",
	"Self Destruction Bot [ROBOT]": "a_55",
	"V01-B01 [ROBOT]": "m_64",
	"Space Commander": "a_56",
	"Seeker of the Light": "m_54",
	"Necromancer Acolyte": "m_55",
	"Beast Emperor [BEASTMAN]": "m_56",
	"Roaring Beast": "evoke_20",
	"Prince of Blood [DEMON] *": "a_57",
	"Prince of Blood [DEMON] **": "a_58",
	"Ambassadress of Peace": "m_57",
	"Blade of Justice": "a_59",
	"Masked Swordsman": "a_60",
	"Beast Champion [BEASTMAN]": "a_61",
	"Beast Guard [BEASTMAN]": "a_62",
	"Desert Queen Cat [BEASTMAN]": "m_58",
	"Lieutenant Armstrong [DEMON]": "a_63",
	"Bear Doll [BEASTMAN]": "evoke_18",
	"Red Bloom [FAIRY]": "m_59",
	"Toxic Flower": "evoke_17",
	"Iron Arm": "a_64",
	"Sigil Essence": "m_60",
	"Lullyp [BEASTMAN][FAIRY]": "a_65",
	"Sun Priestess": "m_61",
	"Elf Recruit [ELF]": "a_66",
	"Blessed Fairy [ANGEL][FAIRY]": "m_62",
	"Oracle of Guardians": "m_63",
	"Thorn Monk": "a_67",
	"Unchained Dino": "a_68",
	"Mecha Dino [ROBOT]": "a_128",
	"Illusionist": "m_65",
	"Old Jester": "m_66",
	"Earth Seed *": "a_70",
	"Earth Seed **": "a_71",
	"Red Drake *": "a_72",
	"Red Drake **": "a_73",
	"Young Mermaid": "a_74",
	"Fairy Princess [FAIRY]": "m_67",
	"Magic Peas": "m_68",
	"Swipe": "druid_beast_1",
	"Bite": "druid_beast_2",
	"Path of the Beast": "druid_beast_3",
	"Aspect of the Beast": "druid_beast_4",
	"Magic Leaf": "m_69",
	"Swamp Plant": "druid_evoke_1",
	"Snake Plant": "druid_evoke_2",
	"Eating Plant": "druid_evoke_3",
	"Sharp Plant": "druid_evoke_4",
	"Iron Plant": "druid_evoke_5",
	"Priest Healer": "a_75",
	"Sonjo the Holy Lancer": "paladin_1",
	"Bjorg the Mace of Justice": "paladin_2",
	"Syra the Lady of Divine Judgment": "paladin_3",
	"Lucie the Lady of Lights": "paladin_4",
	"Viking Warrior": "barbarian_1",
	"Daughter of the Tribe": "barbarian_2",
	"Tribe Elder": "barbarian_3",
	"Erax": "m_103",
	"Thanatox": "m_104",
	"Captain of the Pirates": "pirate_1",
	"Captain Treasure": "pirate_chest",
	"Rusty Gun": "treasure_1",
	"Cursed Coin": "treasure_2",
	"Rum Flask": "treasure_3",
	"Old Mandolin": "treasure_4",
	"Golden Cup": "treasure_5",
	"Village Chief": "shaman_1",
	"Village Elite": "shaman_2",
	"Daughter of Fire": "shaman_3",
	"Ship's Boy": "pirate_2",
	"Pirate Gunner": "pirate_3",
	"Buccaneer": "pirate_4",
	"Portal of Secrets": "secret_door",
	"Spirit of Combat [ANCIENT] *": "a_77",
	"Spirit of Combat [ANCIENT] **": "a_78",
	"Spirit of Magic [ANCIENT] *": "m_71",
	"Spirit of Magic [ANCIENT] **": "m_72",
	"Spirit of Defense [ANCIENT] *": "a_79",
	"Spirit of Defense [ANCIENT] **": "a_80",
	"Legendary Spirit [ANCIENT] ***": "a_81",
	"Angel Captain [ANGEL]": "a_76",
	"Angel Strategist [ANGEL]": "m_73",
	"Blessed Lady [ANGEL]": "m_74",
	"Angel Assistant [ANGEL]": "a_82",
	"Portia, Keeper of Silence [ANCIENT][ANGEL]": "a_83",
	"Azahr, the Exiled Wizard [ANCIENT]": "m_75",
	"Cualdir, Ethereal Blade [ANCIENT]": "a_84",
	"Cthool, the Darkmaster [ANCIENT]": "a_85",
	"Alestar, Tranquility Defender [ANCIENT]": "a_86",
	"Airielle, Free Spirit [ANCIENT]": "a_87",
	"Melgaroth, Keeper of Flames [ANCIENT][DEMON]": "m_76",
	"Sou, The Blade of Wind [ANCIENT]": "a_88",
	"Keyra, The Shy Soul [ANCIENT]": "m_78",
	"Dhorion, Holy Sentinel [ANCIENT]": "a_90",
	"Young Fox [BEASTMAN]": "a_36",
	"Cthool Apprentice": "m_79",
	"Heroic Blacksmith": "a_91",
	"Mad Scientist": "m_80",
	"Centaur Fighter [BEASTMAN][ELF]": "a_38",
	"Gorgrirath [DEMON]": "a_93",
	"Barrerath [DEMON]": "a_94",
	"Masked Horror": "a_95",
	"Penguin King": "a_96",
	"Red Witch": "m_82",
	"Blue Witch": "m_83",
	"Ixar Order of the Wizards": "m_81",
	"Xatior Order of the Wizards": "m_84",
	"Great Wizard": "m_85",
	"Space Fighter *": "a_97",
	"Space Fighter **": "a_98",
	"Goading Goblin": "a_99",
	"Dagger Master": "a_100",
	"Mystic Bird": "m_86",
	"Magic Fox *": "m_87",
	"Magic Fox **": "m_88",
	"Magic Bird *": "m_89",
	"Magic Bird **": "m_90",
	"Magic Cat *": "m_91",
	"Magic Cat **": "m_92",
	"Great Chimera ***": "m_93",
	"Rune King": "rune_1",
	"Rune Queen": "rune_2",
	"Rune Elite": "rune_3",
	"Rune Protector": "rune_4",
	"Green Rune Fragment": "rune_green_evoke",
	"Red Rune Fragment": "rune_red_evoke",
	"Blue Rune Fragment": "rune_blu_evoke",
	"Yellow Rune Fragment": "rune_yellow_evoke",
	"Robotic Parts (v1) *": "a_101",
	"Robotic Parts (v2) *": "a_102",
	"Robotic Parts (v3) *": "a_103",
	"Robotic Parts (v4) *": "a_104",
	"Robotic Parts (v5) *": "a_105",
	"Super Ultimate Robot [ROBOT] ***": "a_106",
	"Sacred Elk": "war_1",
	"Provoking Bird": "war_2",
	"Tree Squirrel": "war_3",
	"Eternal Guardian": "war_4",
	"Feral Guardian": "war_5",
	"Fire Totem": "totem_fire",
	"Thunder Totem": "totem_thunder",
	"Earth Totem": "totem_toxic",
	"Water Totem": "totem_water",
	"Apprentice Healer": "m_70",
	"Elven Parrot *": "m_97",
	"Elven Parrot **": "m_98",
	"Parrot Trainer [ELF]": "m_95",
	"Forest Healer [ELF]": "m_96",
	"Elf Squire [ELF]": "a_112",
	"Grey Elf [ELF]": "a_109",
	"Sharpshoter Elf [ELF]": "a_110",
	"Ailon Lord of the Forest [ELF]": "a_113",
	"Eldon of the High Elves [ELF]": "a_111",
	"Galidel Lady of the Wood [ELF]": "m_94",
	"Laercolas Bow Master [ELF]": "a_114",
	"Pumpkin Master": "e_halloween_4",
	"Explosive Pumpkin": "e_halloween_6",
	"Captain of the Cursed": "pirate_cursed_1",
	"Ship's Boy": "pirate_cursed_2",
	"Pirate Gunner": "pirate_cursed_3",
	"Buccaneer": "pirate_cursed_4",
	"Skeleton Piranha": "necro_5",
	"Half Orc Outlander": "barbarian_ho_1",
	"Half Orc Fighter": "barbarian_ho_2",
	"Half Orc Sorcerer": "barbarian_ho_3",
	"Beast Marshal [BEASTMAN]": "m_99",
	"Beast Commander [BEASTMAN]": "a_116",
	"Guard Captain [BEASTMAN]": "a_117",
	"Beast Protector [BEASTMAN]": "a_118",
	"Wildcat Fighter [BEASTMAN]": "a_115",
	"Blessed Kitty Cat": "m_100",
	"Elite Fighter": "warr_fighter",
	"Elite Guard": "warr_defender",
	"Acolyte of Light": "cultist_l_1",
	"Lightsworn Fighter": "cultist_l_2",
	"Older Sister of Dawn": "cultist_l_3",
	"Younger Sister of Dawn": "cultist_l_4",
	"High Priest of the Dawn": "cultist_l_5",
	"Archangel [ANGEL]": "cultist_l_6",
	"Acolyte of Dark": "cultist_d_1",
	"Blood Fighter": "cultist_d_2",
	"Brother of the Night": "cultist_d_3",
	"Sister of the Night": "cultist_d_4",
	"High Priest of the Blood Moon": "cultist_d_5",
	"Archdevil [DEMON]": "cultist_d_6",
	"Zombie Siren": "m_101",
	"Zombie Shepherd": "m_102",
	"Zombie Dog": "a_121",
	"Silver Forest Guardian [ELF]": "a_122",
	"Ghoul Knight": "a_123",
	"Ghoul Wizard": "m_105",
	"Progeny of Cthool": "m_106",
	"Ant Queen [BEASTMAN]": "m_107",
	"Red Dino Warrior": "a_124",
	"Green Dino Warrior": "a_125",
	"Purple Dino Warrior": "a_126",
	"Yellow Dino Warrior": "a_127",
	"Hippocampus": "m_108",
	"Star Commando": "a_129",
	"Star Marshal": "a_130",
	"Space Assassin": "a_131",
	"Death Squad Captain": "a_132",
	"Undead Assassin": "a_133",
	"Undead Red Wizard": "m_109",
	"Undead Blue Wizard": "m_110",
	"Flame Champion [ANCIENT]": "a_134",
	"Geyser Eel": "a_135",
	"Desert Cactus": "a_136",
	"Scared Snail": "a_137",
	"Heroic Demon Warrior [DEMON]": "a_138",
	"Sesshuma, Shepherd of Souls [ANCIENT]": "m_111",
	"Stealth Assassin [ANCIENT]": "a_139",
	"Fairy Fish": "evoke_fill_fairy",
	"Mushroom Spores": "evoke_spores",
	"Star Fish": "evoke_fill",
	"Void Globe": "evoke_void",
	"Genie Lamp": "evoke_14",
	"Lady Genie": "evoke_12",
	"Mr Genie": "evoke_13",
	"Corrupted Skeleton": "evoke_19",
	"Red Fish": "evoke_15",
	"Evil Berries": "evoke_16",
};
