const heroSkills = {
	"warrior": "skill_warrior",
	"assassin": "skill_assassin",
	"paladin": "skill_paladin",
	"wizard": "skill_wizard",
	"necromancer": "skill_necromancer",
	"shaman": "skill_shaman",
	"ranger": "skill_ranger",
	"druid": "skill_druid",
	"engineer": "skill_engineer",
	"diamond shield": "skill_1",
	"knowledge of strength": "skill_2",
	"knowledge of resistance": "skill_3",
	"luxury gift": "skill_4",
	"toxic wall": "skill_5",
	"burning wall": "skill_6",
	"frost nova": "skill_7",
	"chain lightning": "skill_8",
	"bones armor": "skill_9",
	"bounty hunter": "skill_10",
	"soul drain": "skill_11",
	"explosive enemies": "skill_12",
	"toxic strike": "skill_13",
	"burning strike": "skill_14",
	"shuriken attack": "skill_15",
	"kunai attack": "skill_16",
	"gold ingot": "skill_17",
	"treasure map": "skill_18",
	"anti-monster mine": "skill_19",
	"telescope": "skill_20",
	"apple pie": "skill_21",
	"torch": "skill_22",
	"growth blessing": "skill_23",
	"potion maker": "skill_24",
	"kraken tentacle": "skill_25",
	"meteor storm": "skill_26",
	"mana battery": "skill_27",
	"ice block": "skill_28",
	"flame aura": "skill_29",
	"life sword": "skill_30",
	"necklace of life": "skill_31",
	"stone skin": "skill_32",
	"devil's deal": "skill_33",
	"wand of combat": "skill_34",
	"wand of magic": "skill_35",
	"mana sword": "skill_36",
	"shield of shadows": "skill_37",
	"fire punch": "skill_38",
	"thunder blast": "skill_39",
	"dark sigil": "skill_40",
	"tower shield": "skill_41",
	"blessing of sanctuary": "skill_42",
	"phoenix feather": "skill_43",
	"shadow wall": "skill_44",
	"dark matter": "skill_45",
	"demon eye": "skill_46",
	"living mana": "skill_47",
	"book of magic": "skill_48",
	"toxic explosion": "skill_49",
	"burning armor": "skill_50",
	"master of toxins": "skill_51",
	"frog leg": "skill_52",
	"fox tail": "skill_53",
	"rabbit paw": "skill_54",
	"phantom boots": "skill_55",
	"pink magic": "skill_56",
	"shadow cage": "skill_57",
	"solid shell": "skill_58",
	"multishot": "skill_59",
	"priest staff": "skill_60",
	"ice king sword": "skill_61",
	"earth punch": "skill_62",
	"dark grasp": "skill_63",
	"golden potion": "skill_64",
	"staff of bones": "skill_65",
	"amulet of healing": "skill_66",
	"circular shield": "skill_67",
	"key of the portal": "skill_68",
	"staff of curses": "skill_69",
	"tear of goddess": "skill_70",
	"opal stone": "skill_71",
	"pickpocket": "skill_72",
	"purple magic": "skill_73",
	"crystal sphere": "skill_74",
	"barbarian": "skill_barbarian",
	"pirate": "skill_pirate",
	"runemaster": "skill_runemaster",
	"invisibility potion": "skill_75",
	"snail shell": "skill_76",
	"acid arrow": "skill_77",
	"toxic aura": "skill_78",
	"perfect crystal": "skill_79",
	"necronomicon": "skill_80",
	"weakening aura": "skill_81",
	"finisher": "skill_82",
	"purple potion": "skill_83",
	"electrostatic field": "skill_84",
	"explosive shot": "skill_85",
	"freezing shot": "skill_86",
	"spear of ghosts": "skill_87",
	"weak vortex": "skill_88",
	"golden shield": "skill_89",
	"toxic globe": "skill_90",
	"piece of coal": "skill_91",
	"cursed arrow": "skill_92",
	"bat wing": "skill_93",
	"bird beak": "skill_94",
	"weak dagger": "skill_95",
	"burn dagger": "skill_96",
	"thunder dagger": "skill_97",
	"rock dagger": "skill_98",
	"mana dagger": "skill_99",
	"sapphire medallion": "skill_100",
	"scorpion claw": "skill_101",
	"roc's feather": "skill_102",
	"forest sigil": "skill_forest",
	"swamp sigil": "skill_swamp",
	"desert sigil": "skill_desert",
	"deep water sigil": "skill_water",
	"volcano sigil": "skill_volcano",
	"lost world sigil": "skill_lostworld",
	"land of dragons sigil": "skill_dragon",
	"reign of the dead sigil": "skill_undead",
	"the void sigil": "skill_void",
	"warden": "skill_warden",
	"cultist": "skill_cultist",
	"gladiator": "skill_gladiator",
	"vial of life": "skill_103",
	"lure": "skill_104",
	"destroyed shield": "skill_105",
	"services voucher": "skill_106",
	"power battery": "skill_107",
	"magician hat": "skill_108",
	"war hatchet": "skill_109",
	"strange potion": "skill_110",
	"block of gems": "skill_111",
	"fully charged": "skill_112",
	"earth trap": "skill_113",
	"wild strawberries": "skill_114",
	"demon blood": "skill_115",
	"sacred tunic": "skill_116",
	"double edged blade": "skill_117",
	"cardpedia": "skill_118",
	"spiked armor": "skill_119",
	"spiked shield": "skill_120",
	"spiked gloves": "skill_121",
	"weakening strike": "skill_122",
	"thunder strike": "skill_123",
	"electrified arrow": "skill_124",
	"circular strike": "skill_125",
	"acid spear": "skill_126",
	"death diary": "skill_127",
	"stone block": "skill_128",
	"sun blessed mace": "skill_129",
	"sun blessed bow": "skill_130",
	"brightest star": "skill_131",
	"piercing flames": "skill_132",
	"infernal skull": "skill_133",
	"leather helmet": "skill_134",
	"leather boots": "skill_135",
	"black shield": "skill_136",
	"heavy helmet": "skill_137",
	"heavy armor": "skill_138",
	"heavy shield": "skill_139",
	"wood elves boots": "skill_140",
	"dark elves boots": "skill_141",
	"toxic leaf": "skill_142",
	"antidote": "skill_143",
	"magic mirror": "skill_144",
	"evoker staff": "skill_145",
	"twin-blade sword": "skill_146",
	"staff of ghosts": "skill_147",
	"shooting target": "skill_148",
	"electrostatic aura": "skill_149",
	"water geyser": "skill_150",
};
